"""
DD-MARI Configuration / DD-MARI 配置文件
Defect-Driven Multi-Agent Rule Induction Framework
缺陷驱动的多智能体规则归纳框架
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# ==================== Paths / 路径 ====================
PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

# Input files (place your ASAP Set 1 data here)
# 输入文件（将 ASAP Set 1 数据放入此目录）
GRADIENT_DATA_FILE  = DATA_DIR / "asap_set1_gradient.xlsx"   # Calibration set (quality-stratified, ~10-20 samples) / 校准集（质量分层，约10-20个样本）
TRAINING_DATA_FILE  = DATA_DIR / "asap_set1_training.xlsx"   # Training pool: original + augmented pairs / 训练池：原始样本 + 增强样本对
TEST_DATA_FILE      = DATA_DIR / "asap_set1_test.xlsx"        # Hold-out test set / 保留测试集
STANDARD_DOC_FILE   = DATA_DIR / "Set1_standard.docx"         # Official ASAP Set 1 scoring guidelines / ASAP Set 1 官方评分标准文档

# Output files / 输出文件
RULE_HISTORY_FILE   = OUTPUT_DIR / "rule_history.json"
FEATURE_LIB_FILE    = OUTPUT_DIR / "feature_library.json"
FINAL_RULE_FILE     = OUTPUT_DIR / "final_rule.json"
EVAL_RESULT_FILE    = OUTPUT_DIR / "evaluation_result.xlsx"

# ==================== LLM Configuration / LLM 配置 ====================
LLM_API_KEY     = os.environ.get("LLM_API_KEY")
LLM_BASE_URL    = os.environ.get("LLM_BASE_URL", "https://api.deepseek.com")
LLM_MODEL_NAME  = os.environ.get("LLM_MODEL_NAME", "deepseek-chat")

# ==================== Algorithm Hyperparameters / 算法超参数 ====================
# Scoring scale / 评分范围
SCORE_MIN = 2
SCORE_MAX = 12

# Phase 1: Contrastive sample construction / 阶段1：对比样本构建
SCORE_MARGIN_THRESHOLD = 2      # δ: max score gap for hard-negative pairs / δ：困难负样本最大分差

# Phase 2: Cold-start initialization / 阶段2：冷启动初始化
NUM_INITIAL_RULES = 3           # N: number of candidate rules generated by SGA / N：SGA 生成的候选规则数

# Phase 3: Iterative optimization / 阶段3：迭代优化
MAX_ITERATIONS = 30             # K: maximum optimization rounds / K：最大优化轮次
ROLLBACK_THRESHOLD = 0.001      # τ: minimum QWK improvement to accept a new rule / τ：接受新规则的最小 QWK 提升量
BATCH_SIZE = 1                  # samples per iteration batch / 每轮迭代处理的样本数
RAG_TOP_K = 5                   # top-k features retrieved from feature library / 从特征库检索的 top-k 特征数
SCORING_THREADS = 8             # parallel threads for batch scoring / 批量评分的并行线程数
ITER_EVAL_SIZE = 100            # |Dcal|: calibration set size for Phase 3 rollback (paper §III-C) / 论文§III-C 阶段3回滚校准集大小
ITER_EVAL_SEED = 42             # random seed for Dcal / holdout split / Dcal/保留集划分的随机种子

# Phase 4: Cognitive alignment (for unstructured/subjective tasks only)
# 阶段4：认知对齐（仅用于非结构化/主观任务）
ENABLE_COGNITIVE_ALIGNMENT = True
# Calibration hyperparameters — Eq.(10) in the paper
# 校准超参数 —— 论文公式(10)
CALIB_KAPPA  = 1.0              # κ: unit mapping amplitude / κ：单位映射幅度
CALIB_ALPHAS = [0.5, 1.2]       # {α_1, α_2}: psychological damping coefficients / {α_1, α_2}：心理阻尼系数

# ==================== Task Mode / 任务模式 ====================
# "structured"   → power grid / compliance documents (alignment disabled)
# "structured"   → 电网/合规文档（禁用认知对齐）
# "unstructured" → essay scoring (alignment enabled)
# "unstructured" → 作文评分（启用认知对齐）
TASK_MODE = "unstructured"

# ==================== Human-in-the-Loop / 人机协作 ====================
# Set True to prompt a domain expert for binary feature validation each iteration
# 设为 True 以在每轮迭代时提示领域专家进行二值特征验证
HUMAN_IN_THE_LOOP = False
